import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/app/components/QueryProvider/QueryProvider";
import { AuthProvider } from "@/app/components/AuthProvider/AuthProvider";
import { AppShell } from "@/app/components/AppShell/AppShell";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
        <AuthProvider>
          <AppShell>{children}</AppShell>
        </AuthProvider>
      </QueryProvider>
      </body>
    </html>
  );
}
